version: '3'
services:
  bot:
    container_name: BCatBot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - catnetwork

networks:
  catnetwork:
    driver: bridge
